/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.supermarket.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.supermarket.controller.CustomerController;
import lk.ijse.supermarket.controller.ItemController;
import lk.ijse.supermarket.controller.OrderController;
import lk.ijse.supermarket.db.DBConnection;
import lk.ijse.supermarket.model.Customer;
import lk.ijse.supermarket.model.Item;
import lk.ijse.supermarket.model.OrderDetail;
import lk.ijse.supermarket.model.Orders;

/**
 *
 * @author DILLKI COORAY
 */
public class PlaceOrderForm extends javax.swing.JFrame {

    /**
     * Creates new form PlaceOrderForm
     */
    public PlaceOrderForm() {
        initComponents();
        setLocationRelativeTo(null);

        //generate order date
        genarateOrderDate();

        //generate order Id
        genarateOrderId();

        //load all customers to combo
        loadAllCustomers();

        //load all items to combo
        loadAllItems();
    }

    private void genarateOrderDate() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String orderDate = sdf.format(date);
        lblOrderDate.setText(orderDate);
    }

    private void genarateOrderId() {
        try {
            Connection connection = DBConnection.getInstance().getConnection();
            Statement stm = connection.createStatement();
            ResultSet rst = stm.executeQuery("SELECT OrderId FROM orders ORDER BY OrderId DESC LIMIT 1");
            if (rst.next()) {
                String orderId = rst.getString(1);
                orderId = orderId.split("[A-Z]")[1];
                orderId = "O" + (Integer.parseInt(orderId) + 1);
                lblOrderId.setText(orderId);
            } else {
                lblOrderId.setText("O0");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllCustomers() {
        try {
            ArrayList<Customer> customers = CustomerController.getAllCustomers();
            for (Customer c : customers) {
                cmbCustomerId.addItem(c.getId());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllItems() {
        try {
            ArrayList<Item> items = ItemController.loadAllItems();
            for (Item i : items) {
                cmbItemCode.addItem(i.getCode());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private int isAlreadyExist(String itemCode) {
        System.out.println("debug5: isalready");
        DefaultTableModel dtm = (DefaultTableModel) tblBill.getModel();
        System.out.println("123");
        System.out.println("debug6: isalready");
        for (int i = 0; i < tblBill.getRowCount(); i++) {
            String code = (String) dtm.getValueAt(i, 0);

            if (code.equals(itemCode)) {
                return i;
            }
            System.out.println("debug7: isalready");
        }

        return -1;
    }

    private void calculateTotal() {
        DefaultTableModel dtm = (DefaultTableModel) tblBill.getModel();

        double total = 0;

        for (int i = 0; i < dtm.getRowCount(); i++) {
            total += (double) dtm.getValueAt(i, 4);
        }
        lblTotal.setText(total + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblQtyOnHand = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        lblOrderDate = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblUnitPrice = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        cmbCustomerId = new javax.swing.JComboBox<>();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        cmbItemCode = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText(" ~~~~~~~~~~~~~~~~~~~~Place Order~~~~~~~~~~~~~~~~~~~~");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 10, 960, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Order Date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Customer Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Customer Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Item Code");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Description");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Unit Price");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Qty On Hand");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Qty");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Total");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Order Id");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 90, -1));

        lblQtyOnHand.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblQtyOnHand.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 110, 40));

        lblOrderId.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblOrderId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, 40));

        lblOrderDate.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblOrderDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblOrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 130, 40));

        lblCustomerName.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblCustomerName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 110, 30));

        lblTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 110, 40));

        lblDescription.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDescription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, 40));

        lblUnitPrice.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblUnitPrice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 120, 40));

        txtQty.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 90, 40));

        cmbCustomerId.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmbCustomerId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCustomerIdItemStateChanged(evt);
            }
        });
        cmbCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCustomerIdActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, 40));

        btnRemove.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        btnAdd.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        btnPlaceOrder.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, -1));

        tblBill.setBackground(new java.awt.Color(51, 51, 0));
        tblBill.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblBill.setForeground(new java.awt.Color(255, 255, 255));
        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Description", "Qty", "Unit Price", "Total"
            }
        ));
        tblBill.setGridColor(new java.awt.Color(255, 0, 102));
        jScrollPane1.setViewportView(tblBill);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 820, 150));

        cmbItemCode.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmbItemCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemCodeItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 40));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("New");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/supermarket/images/a1.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 320));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/supermarket/images/gar 1.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 260, 240));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/supermarket/images/images (4).jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 280, 260));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/supermarket/images/images (6).jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 250, 200));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("********************************************************************************************************");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 940, -1));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 670, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBill.getSelectedRow();

        if (selectedRow == -1) {
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblBill.getModel();
        dtm.removeRow(selectedRow);

        calculateTotal();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void cmbCustomerIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCustomerIdItemStateChanged
        // TODO add your handling code here:
        try {
            String customerId = cmbCustomerId.getSelectedItem().toString();
            Customer customer = CustomerController.searchCustomer(customerId);
            lblCustomerName.setText(customer.getName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbCustomerIdItemStateChanged

    private void cmbItemCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemCodeItemStateChanged
        // TODO add your handling code here:
        try {
            String itemCode = cmbItemCode.getSelectedItem().toString();
            Item item = ItemController.searchItem(itemCode);
            lblDescription.setText(item.getDescription());
            lblUnitPrice.setText(item.getUnitPrice() + "");
            lblQtyOnHand.setText(item.getQtyOnHand() + "");

            txtQty.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbItemCodeItemStateChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        System.out.println("ActionEventStart");
// TODO add your handling code here:
        System.out.println("Debug1: btnAdd");
        DefaultTableModel dtm = (DefaultTableModel) tblBill.getModel();
        System.out.println("Debug2: btnAdd");

        int qty = Integer.parseInt(txtQty.getText());
        double unitPrice = Double.parseDouble(lblUnitPrice.getText());
        double total = unitPrice * qty;
        System.out.println("Debug3: btnAdd");
        int row = isAlreadyExist(cmbItemCode.getSelectedItem().toString());
        System.out.println("debug4");
        if (row == -1) {
            Object[] rowData = {cmbItemCode.getSelectedItem().toString(), lblDescription.getText(), qty, unitPrice, total};
            dtm.addRow(rowData);
        } else {
            qty += (int) dtm.getValueAt(row, 2);
            total = qty * unitPrice;

            tblBill.setValueAt(qty, row, 2);
            tblBill.setValueAt(total, row, 4);
        }
        System.out.println("Debug4: btnAdd");

        cmbItemCode.requestFocus();
        calculateTotal();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        String orderId = lblOrderId.getText();
        String orderDate = lblOrderDate.getText();
        String customerId = (String) cmbCustomerId.getSelectedItem();
        ArrayList<OrderDetail>orderDetailList=new ArrayList<>();
        
        DefaultTableModel dtm = (DefaultTableModel) tblBill.getModel();
        
        for (int i = 0; i < dtm.getRowCount(); i++) {
            String itemCode = (String) dtm.getValueAt(i, 0);
            int orderQty = (int) dtm.getValueAt(i, 2);
            double unitPrice = (double) dtm.getValueAt(i, 3);
            OrderDetail orderDetail = new OrderDetail(orderId, itemCode, orderQty, unitPrice);
            orderDetailList.add(orderDetail);
        }
        
        Orders orders = new Orders(orderId, orderDate, customerId, orderDetailList);
        
        try {
            boolean isAdded = OrderController.addOrder(orders);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Success");
            } else {
                JOptionPane.showMessageDialog(this, "Added Fail");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        /*try {
            Connection connection = DBConnection.getInstance().getConnection();
            DefaultTableModel dtm = (DefaultTableModel) tblBill.getModel();

            PreparedStatement orderInsert = connection.prepareStatement("INSERT INTO orders VALUES(?,?,?)");
            orderInsert.setObject(1, lblOrderId.getText());
            orderInsert.setObject(2, lblOrderDate.getText());
            orderInsert.setObject(3, cmbCustomerId.getSelectedItem().toString());
            orderInsert.executeUpdate();

            PreparedStatement insertItemDetail = connection.prepareStatement("INSERT INTO orderDetail VALUES(?,?,?,?)");
            for (int i = 0; i < dtm.getRowCount(); i++) {
                insertItemDetail.setObject(1, lblOrderId.getText());
                insertItemDetail.setObject(2, tblBill.getValueAt(i, 0));
                insertItemDetail.setObject(3, tblBill.getValueAt(i, 2));
                insertItemDetail.setObject(4, tblBill.getValueAt(i, 3));
                insertItemDetail.executeUpdate();
            }

            PreparedStatement updateItemQty = connection.prepareStatement("UPDATE item SET qtyOnHand=qtyOnHand-? WHERE ItemCode=?");
            for (int i = 0; i < dtm.getRowCount(); i++) {
                updateItemQty.setObject(1, tblBill.getValueAt(i, 2));
                updateItemQty.setObject(2, tblBill.getValueAt(i, 0));
                updateItemQty.executeUpdate();
            }

            JOptionPane.showMessageDialog(rootPane, "Order Placed!");

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Order Place Failed!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Order Place Failed!");
        }*/
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new CustomerForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCustomerIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbCustomerId;
    private javax.swing.JComboBox<String> cmbItemCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblQtyOnHand;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
