/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.supermarket.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.supermarket.controller.CustomerController;
import lk.ijse.supermarket.controller.ItemController;
import lk.ijse.supermarket.model.Customer;
import lk.ijse.supermarket.model.Item;
import lk.ijse.supermarket.model.Orders;

/**
 *
 * @author DILLKI COORAY
 */
public class ReportForm extends javax.swing.JFrame {

    /**
     * Creates new form ReportForm
     */
    public ReportForm() {
        initComponents();
        
       // loadOrderDate();
        
    }
   /* private void loadOrderDate() {
        try {
            ArrayList<Orders> orders = ItemController.getOrderDate();
            for (Orders i : orders) {
                cmbOrderDate.addItem(i.getOrderDate());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIncome = new javax.swing.JTable();
        btnIncome = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMostMovable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCustomerIncome = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLeast = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Analytical Report");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Daily Income");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Most and Least Movable  Item");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Customer wise Income");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        tblIncome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Date", "Income"
            }
        ));
        jScrollPane1.setViewportView(tblIncome);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 510, 80));

        btnIncome.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnIncome.setText("Get Income");
        btnIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        tblMostMovable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Most Movable Item", "Count"
            }
        ));
        jScrollPane2.setViewportView(tblMostMovable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 360, 80));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Get Most Movable Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        tblCustomerIncome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Income"
            }
        ));
        jScrollPane3.setViewportView(tblCustomerIncome);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 470, 90));

        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setText("Get Detail");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, -1, -1));

        tblLeast.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Least Movable Item", "Count"
            }
        ));
        jScrollPane4.setViewportView(tblLeast);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 390, 80));

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/supermarket/images/54be9e27eaa7fd4c1f24fcca95fdbe35.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 400, 300));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/supermarket/images/54be9e27eaa7fd4c1f24fcca95fdbe35.png"))); // NOI18N
        jLabel5.setText("jLabel3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 400, 300));

        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setText("Get Least Movable Items");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncomeActionPerformed
        // TODO add your handling code here:
       //String sql= "select OrderDate,sum(UnitPrice*OrderQTY) as Total from Orders,OrderDetail where Orders.OrderId=OrderDetail.OrderID group by Orders.OrderDate";
       
       String SQL= "select OrderDate,sum(UnitPrice*OrderQTY) as Total from Orders,OrderDetail where Orders.OrderId=OrderDetail.OrderID group by Orders.OrderDate";
       try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            //
        }
       try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/Wholesale", "root", "1234");
                Statement stm = connection.createStatement();
                ResultSet rst = stm.executeQuery(SQL);
                DefaultTableModel dtm=(DefaultTableModel) tblIncome.getModel();
                dtm.setRowCount(0);
                while(rst.next()){
                   Object[] rowData={rst.getString("OrderDate"),rst.getString("Total")};                   
                   dtm.addRow(rowData);
                }
                        
        } catch (SQLException ex) {
            Logger.getLogger(ReportForm.class.getName()).log(Level.SEVERE, null, ex);
        }       
       
       
    }//GEN-LAST:event_btnIncomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String SQL= "Select Description,count(OrderDetail.OrderId) as Count  From OrderDetail , Item  Where OrderDetail.ItemCode=Item.ItemCode Group by OrderDetail.ItemCode order by 2 desc limit 1;";
        //String SQL1="Select Description,count(OrderDetail.OrderId) as Count  From OrderDetail , Item  Where OrderDetail.ItemCode=Item.ItemCode Group by OrderDetail.ItemCode order by 2 asc limit 1";
       try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            //
        }
       try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/Wholesale", "root", "1234");
                Statement stm = connection.createStatement();
                ResultSet rst = stm.executeQuery(SQL);
                DefaultTableModel dtm=(DefaultTableModel) tblMostMovable.getModel();
                dtm.setRowCount(0);
                while(rst.next()){
                   Object[] rowData={rst.getString("Description"),rst.getString("Count")};                   
                   dtm.addRow(rowData);
                }
                
                /*Statement stm1 = connection.createStatement();
                ResultSet rst1 = stm1.executeQuery(SQL1);
                DefaultTableModel dtm1=(DefaultTableModel) tblLeast.getModel();
                dtm1.setRowCount(0);
                while(rst1.next()){
                   Object[] rowData={rst1.getString("Description"),rst1.getString("Count")};                   
                   dtm1.addRow(rowData);
                }*/
                
                        
        } catch (SQLException ex) {
            Logger.getLogger(ReportForm.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String SQL= "select CustId,sum(UnitPrice*OrderQTY) as Income from Orders,OrderDetail where Orders.OrderId=OrderDetail.OrderID group by Orders.CustId";
       try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            //
        }
       try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/Wholesale", "root", "1234");
                Statement stm = connection.createStatement();
                ResultSet rst = stm.executeQuery(SQL);
                DefaultTableModel dtm=(DefaultTableModel) tblCustomerIncome.getModel();
                dtm.setRowCount(0);
                while(rst.next()){
                   Object[] rowData={rst.getString("CustId"),rst.getString("Income")};                   
                   dtm.addRow(rowData);
                }
                        
        } catch (SQLException ex) {
            Logger.getLogger(ReportForm.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        //String SQL= "Select Description,count(OrderDetail.OrderId) as Count  From OrderDetail , Item  Where OrderDetail.ItemCode=Item.ItemCode Group by OrderDetail.ItemCode order by 2 desc limit 1;";
        String SQL1="Select Description,count(OrderDetail.OrderId) as Count  From OrderDetail , Item  Where OrderDetail.ItemCode=Item.ItemCode Group by OrderDetail.ItemCode order by 2 asc limit 1";
       try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            //
        }
       try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/Wholesale", "root", "1234");
               /* Statement stm = connection.createStatement();
                ResultSet rst = stm.executeQuery(SQL);
                DefaultTableModel dtm=(DefaultTableModel) tblMostMovable.getModel();
                dtm.setRowCount(0);
                while(rst.next()){
                   Object[] rowData={rst.getString("Description"),rst.getString("Count")};                   
                   dtm.addRow(rowData);
                }*/
                
                Statement stm1 = connection.createStatement();
                ResultSet rst1 = stm1.executeQuery(SQL1);
                DefaultTableModel dtm1=(DefaultTableModel) tblLeast.getModel();
                dtm1.setRowCount(0);
                while(rst1.next()){
                   Object[] rowData={rst1.getString("Description"),rst1.getString("Count")};                   
                   dtm1.addRow(rowData);
                }
                
                        
        } catch (SQLException ex) {
            Logger.getLogger(ReportForm.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
     
                
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                */
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new ReportForm().setVisible(true);
                    }
                });
            }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblCustomerIncome;
    private javax.swing.JTable tblIncome;
    private javax.swing.JTable tblLeast;
    private javax.swing.JTable tblMostMovable;
    // End of variables declaration//GEN-END:variables
}
